spring:
  application:
    name: dumpRecover
  data:
    mongodb:
      uri: mongodb://111.229.89.244:27017/test


eureka:
  instance:
    hostname: localhost
    instance-id: dumpRecover
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://111.229.89.244:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 10000

mongo:
  host: 111.229.89.244
  port: 27017
  user: admin
  password: admin


server:
  port: 8080
